package id42.cdk.chat.es;

import java.util.List;

public class LocationSlotTypeES {
    public static List<String> values(){
        return VALUES;
    }

    public static final List<String> VALUES = List.of(
            "Muntaner 321",
            "c/ Muntaner 321",
            "Arco del Triunfo",
            "Napols 630, esc der, 1a",
            "c. Napols 630, esc der, 1a",
            "carrer de Napols 630, esc der, 1a",
            "Bar Celona",
            "Provença con Passeig de Gracia",
            "Carrer de la Diputació, 280",
            "Carrer de la Diputació, 280, 1a",
            "Avendia Diagonal, 630",
            "esquina de napols con industria",
            "Eric & Benajamin",
            "Lucy & Liu",
            "Sara & Sara",
            "Jack & Jull",
            "Fast Kibuka Torrent de l'olla",
            "Fast Kibuka Mayor de Gracia",
            "Bosàbé a Holmes Place Urquinaona",
            "Bosàbé a Holmes Place Passeig de Gracia",
            "Eric Benjamin",
            "Rare",
            "Delacrem",
            "Primero Primera, Raffaelli y Tragaluz",
            "Llet Crua",
            "Muy Buenas, Primero Primera y Casa Sagnier",
            "Catering Eva",
            "Calle Sepúlveda 134",
            "Calle Corsega 134",
            "Calle Roselló 134",
            "Calle del Mar, 12",
            "Plaça de Sant Jaume, 3",
            "Passeig de Gràcia, 85",
            "Carrer de la Boqueria, 31",
            "Avinguda Diagonal, 477",
            "Carrer del Consell de Cent, 290",
            "Carrer de Pau Claris, 117",
            "Plaça de Catalunya, 9",
            "Passeig de Sant Joan, 108",
            "Carrer de Pau Casals, 24",
            "Plaça de Sant Felip Neri, 5",
            "Carrer de Pau Claris, 174",
            "Passeig de Sant Gervasi, 48",
            "Carrer de Balmes, 190",
            "Avinguda de la Catedral, 7",
            "Carrer de Pau Claris, 187",
            "Passeig de Gracia, 112",
            "Plaça del Pi, 3",
            "Carrer de Pau Claris, 123",
            "Avinguda Diagonal, 632",
            "Passeig de Sant Joan, 78",
            "Carrer de Pau Claris, 61",
            "Carrer de Pau Claris, 86",
            "Plaça de Sant Jaume, 11",
            "Passeig de Sant Joan, 96",
            "Avinguda de la Catedral, 17",
            "Passeig de Gracia, 150",
            "Carrer de Pau Claris, 109",
            "Plaça de Sant Felip Neri, 8",
            "Carrer de Pau Claris, 141",
            "Passeig de Sant Joan, 134",
            "Avinguda Diagonal, 543",
            "Carrer de Pau Claris, 198",
            "Passeig de Gracia, 199",
            "Plaça del Pi, 9",
            "Carrer de Pau Claris, 176",
            "Passeig de Sant Joan, 72",
            "Avinguda de la Catedral, 29",
            "Passeig de Gracia, 125",
            "Carrer de Pau Claris, 155"
    );
}
