name: deploy-main-to-staging

on:
  push:
    branches:
      - 'main'

jobs:
  all-steps:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          #TODO: Replace with IAM Role https://github.com/aws-actions/configure-aws-credentials
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install CDK
        run: npm install -g aws-cdk

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Flutter webapp
        run: flutter build web --release
        working-directory: id42_app

      - name: Build Core package
        run: mvn -B install
        working-directory: id42_entity

      - name: Build API package
        run: mvn -B install
        working-directory: id42_api

      - name: Build bot package
        run: mvn -B install
        working-directory: id42_bot

      - name: Deploy CDK infrastructure
        run: cdk deploy --context envName=staging --require-approval=never
        working-directory: id42_cdk
        env:
          ID42_BOT_TOKEN: ${{ secrets.ID42_BOT_TOKEN }}
          ID42_BOT_USERNAME: ${{ secrets.ID42_BOT_USERNAME }}


