name: deploy-main-to-staging

on:
  push:
    branches:
      - 'main'

jobs:
  all-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          #TODO: Replace with IAM Role https://github.com/aws-actions/configure-aws-credentials
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - uses: graalvm/setup-graalvm@v1
        with:
            version: 'latest'
            java-version: '17'
            components: 'native-image'
            github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install CDK
        run: npm install -g aws-cdk

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build All
        run: ./install.sh

      - name: Deploy All
        run: ./deploy.sh
        env:
          ID42_BOT_TOKEN: ${{ secrets.ID42_BOT_TOKEN }}
          ID42_BOT_USERNAME: ${{ secrets.ID42_BOT_USERNAME }}
          BOT_LEX_BOT_ALIAS_ID: TPQJHRB1QN
          BOT_LEX_BOT_ID: AHADJC9MFT

      - name: Store build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bot_jacoco
          path: |
            id42_bot/target/jacoco-report
